const INTERVIEW_STAGES = {
  NOT_STARTED: "not_started",
  UNDERSTANDING: "understanding",
  CONSTRAINTS: "constraints",
  APPROACH: "approach",
  PSEUDOCODE: "pseudocode",
  CODING: "coding",
  ANALYSIS: "analysis",
  COMPLETED: "completed",
  REPORT_GENERATED: "report_generated",
};

const STAGE_FLOW = [
  INTERVIEW_STAGES.NOT_STARTED,
  INTERVIEW_STAGES.UNDERSTANDING,
  INTERVIEW_STAGES.CONSTRAINTS,
  INTERVIEW_STAGES.APPROACH,
  INTERVIEW_STAGES.PSEUDOCODE,
  INTERVIEW_STAGES.CODING,
  INTERVIEW_STAGES.ANALYSIS,
  INTERVIEW_STAGES.COMPLETED,
  INTERVIEW_STAGES.REPORT_GENERATED,
];



module.exports = {
  INTERVIEW_STAGES,
  STAGE_FLOW,
};
